### ISSUE TITLE
Group links contain characters that are not URL safe

### ISSUE THREAD

**Issue by mattantonelli** [ufx/GarlandTools#40]
Sharing links to item groups on websites like Reddit encodes characters that are not URL safe, which consequently breaks the link.

In the example below, copy-pasting the link text works, but clicking the link itself does not:

http://www.garlandtools.org/db/#group/Ironworks{#item/15515|#item/15516}

Clicking the link yields the following error:

```
TypeError: Cannot read property '1' of null
    at Object.parseHashQuery (http://www.garlandtools.org/db/js/gt.core.js:428:51)
    at Object.loadBlockFromHash (http://www.garlandtools.org/db/js/gt.core.js:471:23)
    at HTMLDocument.initialize (http://www.garlandtools.org/db/js/gt.core.js:55:17)
    at j (https://code.jquery.com/jquery-2.1.4.min.js:2:26925)
    at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.4.min.js:2:27738)
    at Function.ready (https://code.jquery.com/jquery-2.1.4.min.js:2:29532)
    at HTMLDocument.I (https://code.jquery.com/jquery-2.1.4.min.js:2:29723)
```

Perhaps you could decode the unsafe characters, or switch to characters that are URL safe? I found [this reference](http://www.blooberry.com/indexdot/html/topics/urlencoding.htm) and used it to construct a safe version of the URL:

http://www.garlandtools.org/db/#group/Ironworks(#item/15515+#item/15516)

**Comment by ufx** [comment]
Thanks for the report.  I've got this fixed locally and will push it out soon.
