### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by JosieNutter** [ufx/GarlandTools#41]
Got this this morning when attempting to reach http://www.garlandtools.org/db/# via bookmark.

TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.getViewModel (http://www.garlandtools.org/db/js/gt.list.js:80:39)
    at Object.redisplayLists (http://www.garlandtools.org/db/js/gt.list.js:66:22)
    at Object.reinitialize (http://www.garlandtools.org/db/js/gt.list.js:31:11)
    at HTMLDocument.initialize (http://www.garlandtools.org/db/js/gt.core.js:56:13)
    at j (https://code.jquery.com/jquery-2.1.4.min.js:2:26925)
    at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.4.min.js:2:27738)
    at Function.ready (https://code.jquery.com/jquery-2.1.4.min.js:2:29532)
    at HTMLDocument.I (https://code.jquery.com/jquery-2.1.4.min.js:2:29723)

Clearing settings DID allow me back into the site, so I don't know if this is moot now or what.

Side note: the message "Oops! Something went wrong. Please copy the below message into a comment at the forums, or submit to our issue tracker" links to https://disqus.com/home/discussion/garlandtools/garland_tools/ for forum, which appears to be closed for new comments.

**Comment by ufx** [comment]
Ah, you probably visited the site a while ago and had some old data cached.  Usually a shift+refresh will clear that up.  Thanks for letting me know about the link too - I'll update that page.
