### ISSUE TITLE
TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by bekaness** [ufx/GarlandTools#43]
at HTMLDocument.initialize (https://www.garlandtools.org/db/js/gt.core.js:50:14)
    at j (https://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:29948)
    at k (https://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:30262)

**Comment by ufx** [comment]
Thanks for the report - this is just a caching issue.  Try holding ctrl+refresh and it'll go away!

**Comment by bekaness** [comment]
Okay thanks. sorry i'm new here and I couldn't quite read the other error names right or something >_>

**Comment by ufx** [comment]
No problem!  I appreciate the reports =)
