### ISSUE TITLE
Error after opening Solstice Garlic

### ISSUE THREAD

**Issue by mkolopanis** [ufx/GarlandTools#44]
Site began to hang then error after trying to open the solstice garlic page:

TypeError: Cannot read property 'initialize' of undefined
    at HTMLDocument.initialize (http://www.garlandtools.org/db/js/gt.core.js:50:14)
    at j (http://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:29948)
    at k (http://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:30262)

**Comment by ufx** [comment]
Hiya, it's definitely a caching issue - try holding ctrl+refresh and it should clear up!
