### ISSUE TITLE
Error on reload on mobile

### ISSUE THREAD

**Issue by SigurdCole** [ufx/GarlandTools#45]
Samsung S6, Chrome v55, Android 5.1.1

TypeError: Cannot read property 'initialize' of undefined
    at HTMLDocument.initialize (http://www.garlandtools.org/db/js/gt.core.js:50:14)
    at j (http://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:29948)
    at k (http://www.garlandtools.org/db/ext/jquery-3.1.1.min.js:2:30262)

**Comment by ufx** [comment]
Hiya, definitely just a caching issue.  Hold ctrl+refresh and it should work!
